### ISSUE TITLE
Issue running the provider

### ISSUE THREAD

**Issue by papapathe** [aaronstillwell/terraform-provider-dokku#1]
Hello thanks for the awesome work you've done here.

I encountered some issues because after login with ssh, the provider was not able to detect the dokku version. I ended up diggin in the code and found that the command was not setup correctly (thanks to basj 127 error code).

I have managed to make it work by 
* making changes locally
* compiling and installing a custom version of the provider. 

I would love to share those and help develop this. 
`
terraform init && terraform apply                                                                                                                  *[main]

Initializing the backend...

Initializing provider plugins...
- Finding latest version of aaronstillwell/dokku...
- Installing aaronstillwell/dokku v0.4.0...
- Installed aaronstillwell/dokku v0.4.0 (self-signed, key ID 48ECD67255C7A987)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
╷
│ Error: Could not detect dokku version - tested version range: >=0.24.0 <0.27.0
│
│   with provider["registry.terraform.io/aaronstillwell/dokku"],
│   on main.tf line 9, in provider "dokku":
│    9: provider "dokku" {
│
╵

Diff of my changes.

`
diff --git a/dokku/provider.go b/dokku/provider.go
index aa59200..11894a9 100644
--- a/dokku/provider.go
+++ b/dokku/provider.go
@@ -130,7 +130,7 @@ func providerConfigure(ctx context.Context, d *schema.ResourceData) (interface{}
                return nil, diag.Errorf("Could not establish SSH connection: %v", err)
        }

-       res := run(client, "version")
+       res := run(client, "dokku version")

        re := regexp.MustCompile("[0-9]+\\.[0-9]+\\.[0-9]+")
        found := re.FindString(res.stdout)
`

`

**Comment by aaronstillwell** [comment]
Hi @papapathe! Thank you for this submission!

If I've understood this correctly, it looks as if you're wanting to provide the `dokku` command from the provider, which seems to suggest you are using a regular user account to SSH into your dokku box?

This provider assumes that you are using a dokku user, and therefore never explicitly provides the `dokku` command via SSH. Documentation on dokku users can be found here: https://dokku.com/docs/deployment/user-management/

Note as far as I can tell, the provider would need to explicitly provide the `dokku` command everywhere, not just to extract the dokku version.

Would you be able to confirm my assumption that you're using a regular SSH user, and if so test again with a dokku user?

Thank you!

**Comment by papapathe** [comment]
Ah right then. I was using a regular ssh user. That's why it was not working. Did i miss something in the README. 

Thanks for the work you've done here, it saved me a lot of time. I know a bit of golang and would love to contribute new features / fixes here. Let me know

**Comment by aaronstillwell** [comment]
I’ll amend the docs accordingly thanks for pointing this out! Contributions
welcome.
