### ISSUE TITLE
Dockerfile deployment

### ISSUE THREAD

**Issue by joe-narvaez** [aaronstillwell/terraform-provider-dokku#11]
**Is your feature request related to a problem? Please describe.**
I need to dockerfile based deployment because I need to tweak some container options using the the dokku  docker plugin.

**Describe the solution you'd like**
```
config_vars  = {
   dockerfile =  true
}
```

**Describe alternatives you've considered**
a bash script to bootstrap dokku

**Comment by aaronstillwell** [comment]
Thanks for the submission @joe-narvaez !

Would you be able to provide some further context as to what dokku settings we need to modify to support this?

I'm looking at [this](https://dokku.com/docs/deployment/builders/dockerfiles/) doc and it looks like dokku automatically detects Dockerfile based deployments, and should be possible with the provider as-is.

There are two settings we could look to support based on that doc.

1. An option to ensure the `DOKKU_PROXY_PORT_MAP` variable is not set as per the note on handling apps that have [previously been deployed with buildpacks](https://dokku.com/docs/deployment/builders/dockerfiles/#switching-from-buildpack-deployments).
2. An option to customize the Dockerfile location per-app via the `builder-dockerfile:set` [option](https://dokku.com/docs/deployment/builders/dockerfiles/#changing-the-dockerfile-location).

Thank you!

**Comment by joe-narvaez** [comment]
@aaronstillwell  thanks for the response.   M apologies for being unclear.  Is there a way I can run docker option plugin commands? I'm trying to add some labels to the container.

**Comment by joe-narvaez** [comment]
I guess I can use the docker provider to add the labels. Sorry to waster your time!
