### ISSUE TITLE
Support inline SSH key

### ISSUE THREAD

**Issue by aaronstillwell** [aaronstillwell/terraform-provider-dokku#16]
**Is your feature request related to a problem? Please describe.**
Using the provider in some environments (e.g terraform cloud?) is challenging given the lack of ability to provide a path to an SSH key. The ability to provide an inline SSH key would allow the use of the provider in such environments where the filesystem cannot be relied upon.

**Describe the solution you'd like**
Provide an inline key e.g `ssh_key_inline` instead of `ssh_cert`.

**Describe alternatives you've considered**

**Additional context**

cc @pawelad @m7mdcc

**Comment by aaronstillwell** [comment]
@pawelad @m7mdcc would either of you be able to provide an example of how you'd leverage this config option? Having an SSH certificate in source obviously does not seem super sensible.

**Comment by pawelad** [comment]
> @pawelad @m7mdcc would either of you be able to provide an example of how you'd leverage this config option? Having an SSH certificate in source obviously does not seem super sensible.

Sorry about not replying earlier, I missed the GitHub email and only saw this now.

I don't think the SSH key should be committed into source, but it could easily be populated from an environment variable.

As I mentioned in the [previous issue](https://github.com/aaronstillwell/terraform-provider-dokku/issues/15), the best example of what I meant is the official `dokku` GitHub Actions workflow:

> Looking at it some more, the official dokku GitHub Action (which by definition runs in a non-local environment) uses the "explicitly pass the SSH key" workflow I described above:
> 
> https://dokku.com/docs/deployment/continuous-integration/github-actions/
> https://github.com/dokku/github-action

You can see the example usage of it here:

https://github.com/pawelad/fakester/blob/76bb1af5acfe4d6a3243b73408ac0b96b964fd11/.github/workflows/deploy.yml#L32-L37

**Comment by aaronstillwell** [comment]
This is now included in `v0.5.0`
